[tool.poetry]
name = "machine-learning-algorithms"
version = "0.1.0"
description = "Classical Machine Learning Algorithms"
authors = ["Deven Kalra"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.0.0"
gym = "^0.26.2"
fastbook = "^0.0.29"
mlx = "^0.16.0"
pytest = "^8.3.1"
pylint = "^3.2.6"
black = {extras = ["jupyter"], version = "^24.4.2"}
dlib = "^19.24.4"
neo4j = "^5.22.0"
opencv-contrib-python = "^4.10.0.84"
postgres = "^4.0"
pgvector = "^0.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
