[tool.poetry]
name = "machine-learning-algorithms"
package-mode = false
version = "0.1.0"
description = "Classical Machine Learning Algorithms"
authors = ["Deven Kalra"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.0.0"
gym = "^0.26.2"
fastbook = "^0.0.29"
mlx = "^0.16.0"
pytest = "^8.3.1"
pylint = "^3.2.6"
black = {extras = ["jupyter"], version = "^24.8.0"}
dlib = "^19.24.4"
neo4j = "^5.22.0"
opencv-contrib-python = "^4.10.0.84"
postgres = "^4.0"
pgvector = "^0.3.2"
plotly = "^5.23.0"
pyqt5 = "^5.15.11"
nltk = "^3.9.1"

spacy = "^3.7.6"
pygame = "^2.6.0"
ollama = "^0.3.2"
openai = "^1.42.0"
flake8 = "^7.1.1"
sphinx = "^8.0.2"
lxml = "^5.3.0"
html5lib = "^1.1"
pandas = "^2.2.2"
scikit-learn = "^1.5.1"
scikit-image = "^0.24.0"
matplotlib = "^3.9.2"
seaborn = "^0.13.2"
dash = "^2.17.1"
mypy = "^1.11.2"
flair = "^0.14.0"
python-imagesearch = "^1.3.0"
coverage = "^7.6.2"
opencv-python = "^4.10.0.84"
gymnasium = {extras = ["all"], version = "^1.0.0"}
tf-keras = "^2.18.0"
flask = "^3.0.3"
tensorflow = "^2.18.0"
isnude = "^0.0.2"
bing-image-downloader = "^1.1.2"
sqlitedict = "^2.1.0"
face-recognition = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
