[tool.poetry]
name = "machine-learning-algorithms"
package-mode=false
version = "0.1.0"
description = ""
authors = ["Deven Kalra"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.1.1"
gymnasium = {extras = ["all"], version = "^1.0.0"}
fastbook = "^0.0.29"
black = {extras = ["jupyter"], version = "^24.10.0"}
flake8 = "^7.1.1"
pytest = "^8.3.3"
mlx = "^0.20.0"
tensorflow = "^2.18.0"
opencv-contrib-python = "^4.10.0.84"
torch = "^2.5.1"
torchvision = "^0.20.1"
tensorflow-hub = "^0.16.1"
tensorflow-datasets = "^4.9.7"
isnude = "^0.0.2"
python-imagesearch = "^1.3.0"
nltk = "^3.9.1"
matplotlib = "^3.9.3"
seaborn = "^0.13.2"
plotly = "^5.24.1"
dash = "^2.18.2"
dask = "^2024.11.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
